# Generated by Django 5.2.16 on 2026-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='request_body',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='sample_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
