# Generated by Django 5.2.16 on 2026-07-23 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_category_tag_apiendpoint_category_apiendpoint_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
